# Craft Release Configuration
# https://getsentry.github.io/craft/configuration/

minVersion: "2.16.0"

versioning:
  policy: auto

changelog:
  filePath: packages/spotlight/CHANGELOG.md
  policy: auto

preReleaseCommand: bash scripts/bump-version.sh

statusProvider:
  name: github
  config:
    contexts:
      - "Merge Artifacts"

requireNames:
  - /^spotlight-/
  - /\.dmg$/

targets:
  - name: npm
    path: packages/spotlight

  - name: github
    tagPrefix: "@spotlightjs/spotlight@"
    includeNames: /^(spotlight-|Spotlight|latest-).*|.*\.(yml|blockmap)$/

  - name: docker
    id: versioned
    source: ghcr.io/getsentry/spotlight
    target: ghcr.io/getsentry/spotlight

  - name: docker
    id: latest
    source: ghcr.io/getsentry/spotlight
    target:
      image: ghcr.io/getsentry/spotlight
      format: "{{{target}}}:latest"
