packages:
  - 'packages/*'

catalog:
  "@fontsource/raleway": ^5.1.0
  "@tailwindcss/vite": ^4.1.11
  "@types/node": ^22.15.21
  "@types/react": ^18.3.11
  "@types/react-dom": ^18.3.0
  "@sentry/astro": ^10.31.0
  "@sentry/core": ^10.31.0
  "@sentry/node": ^10.31.0
  react: ^18.3.1
  react-dom: ^18.3.1
  tailwindcss: ^4.1.10
  typescript: ^5.6.2
  vite: ^5.4.21
  vitest: ^0.34.6
