# Changelog Preview workflow
# Shows how PRs will appear in the changelog
# https://getsentry.github.io/craft/

name: Changelog Preview
on:
  pull_request_target:
    types: [opened, synchronize, reopened, edited, labeled, unlabeled]

permissions:
  contents: read
  pull-requests: write
  statuses: write

jobs:
  changelog-preview:
    name: Preview Changelog
    uses: getsentry/craft/.github/workflows/changelog-preview.yml@f4889d04564e47311038ecb6b910fef6b6cf1363 # v2
    secrets: inherit
